[tool.poetry]
name = "kurs-4"
version = "0.1.0"
description = ""
authors = ["AnnaK <njutcka@yandex.ru>"]
readme = "README.md"
packages = [{include = "kurs_4"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
